### ISSUE TITLE
晴海運河の日本語表記がおかしい

### ISSUE THREAD

**Issue by naogify** [geolonia/midnight#6]
https://deploy-preview-7--style-midnight.netlify.app/#18.78/35.6565899/139.7893077

<img width="460" alt="スクリーンショット 2021-06-23 9 18 04" src="https://user-images.githubusercontent.com/8760841/123015764-08f28000-d404-11eb-939c-f48e6ea4fe03.png">

**Comment by keichan34** [comment]
https://www.openstreetmap.org/way/285695006#map=17/35.65629/139.78936

OSMを修正したほうが良いのかな。。

**Comment by naogify** [comment]
確かにですね。OSM修正しました!
https://www.openstreetmap.org/way/285695006#map=17/35.65629/139.78936

**Comment by keichan34** [comment]
@naogify すみません、こちら確認したらどっちの名前も正しく、地図的には両方入ったほうが正しいと思います。

* [晴海運河](https://ja.wikipedia.org/wiki/%E6%99%B4%E6%B5%B7%E9%81%8B%E6%B2%B3)
* [OSM上のセミコロンの扱いについて](https://wiki.openstreetmap.org/wiki/JA:%E3%82%BB%E3%83%9F%E3%82%B3%E3%83%AD%E3%83%B3%E3%81%AB%E3%82%88%E3%82%8B%E5%80%A4%E5%8C%BA%E5%88%87%E3%82%8A)

大変お手数を掛けますが、OSMの変更を戻してもらえますか？私が「修正したほうが良いのかなと」言ったときにちゃんと確認すればよかった。。。ごめんなさい。

地図表示上の扱いについては、セミコロンで「複数の値を必要とする場合」に使われるので、タイル生成時にセミコロンで指定されている一番最初の値を読み込めばこのイシューが解決できると思います。

**Comment by naogify** [comment]
了解しました。自分もちゃんと確認して消せば良かったです、、、💦。

戻しておきます！

**Comment by naogify** [comment]
この件、元に戻しておきました…！
https://www.openstreetmap.org/edit?way=285695006#map=19/35.65565/139.78938

**Comment by naogify** [comment]
Closed by https://github.com/geolonia/tilemaker-geolonia/issues/6
