### ISSUE TITLE
東シナ海が英語表記になっている

### ISSUE THREAD

**Issue by naogify** [geolonia/midnight#8]
https://deploy-preview-7--style-midnight.netlify.app/#10.21/29.0014/124.9979

<img width="1440" alt="スクリーンショット 2021-06-23 9 33 10" src="https://user-images.githubusercontent.com/8760841/123016779-4eb04800-d406-11eb-9939-4b246b1b343e.png">

東シナ海のデータ情報

`source: https://api.geolonia.com/v2/sources` 
`source-layer: water_name`
スタイルレイヤー `water-name-other"`

**Comment by keichan34** [comment]
あ、おそらくこれは大丈夫かと。
cdn でデプロイするときは、 `{name}` のところを ja/en に分けて、 ja の場合は `name:ja` を表示させ、 en の場合は `name:en, name` の順で読み込むと思う
