### ISSUE TITLE
海上のboundary レイヤーを追加

### ISSUE THREAD

**Issue by naogify** [geolonia/midnight#9]
`https://api.geolonia.com/v1/sources` には、海上の `bounadry` レイヤーが含まれていますが、

https://editor.geolonia.com/#9.23/34.6025/139.8914

<img width="1245" alt="スクリーンショット 2021-06-23 12 58 29" src="https://user-images.githubusercontent.com/8760841/123033438-ba081300-d422-11eb-939a-ef2da0d68061.png">

`https://tileserver.geolonia.com/v2/tiles.json` には、海上の`bounadry` レイヤーがありません。`midnight`スタイルでは 海上の`boudary` レイヤーを使うので追加したいです。

https://deploy-preview-7--style-midnight.netlify.app/#9.42/35.6476/140.9467

<img width="1040" alt="スクリーンショット 2021-06-23 13 02 51" src="https://user-images.githubusercontent.com/8760841/123033973-a27d5a00-d423-11eb-97ba-2030e786442a.png">

**Comment by naogify** [comment]
gsi のように海上の`boundary`レイヤーを含むカスタムタイルを作るのが良いかな、、？

**Comment by keichan34** [comment]
いえ、、これはv2に追加したほうが良さそうですね。。

**Comment by keichan34** [comment]
あ、なるほど。 boundary レイヤ自体は入ってるけど maritime=1 のが入ってないのか

**Comment by naogify** [comment]
気になったのですが、`v1` は海上の `boundary-land-level-4`が表示されているのに、`v2` では表示されてないので、陸上かどうかの条件分岐があたったりするのかも。

attribute なのかタイル生成時になのか、つっこんで調べれてないので後で、もう一度見てみます。


### v1

https://editor.geolonia.com/#8.96/34.8114/139.6569

<img width="1243" alt="スクリーンショット 2021-06-23 13 32 29" src="https://user-images.githubusercontent.com/8760841/123036124-8085d680-d427-11eb-899f-82382ebc769c.png">


### v2 

https://deploy-preview-7--style-midnight.netlify.app/#8.96/34.8114/139.6569

<img width="1440" alt="スクリーンショット 2021-06-23 13 33 54" src="https://user-images.githubusercontent.com/8760841/123036259-ba56dd00-d427-11eb-9f9c-c562edfb5999.png">

**Comment by keichan34** [comment]
https://github.com/geolonia/tilemaker-geolonia/commit/ba3e96818cb3e052912d0f191a5f8892825cfb5d これで解決できるか試してみましょうか

**Comment by naogify** [comment]
@keichan34 
`boundary-water` 確認できました。ありがとうございます!

 Closed by https://github.com/geolonia/tilemaker-geolonia/commit/ba3e96818cb3e052912d0f191a5f8892825cfb5d
